import { Link } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { Rocket, Sparkles, ShieldCheck, QrCode, Gauge, Wand2 } from "lucide-react";

export default function Home() {
  return (
    <>
      {/* Hero */}
      <section className="relative overflow-hidden p-12 pt-0">
        <div className="absolute inset-0 bg-grid bg-size-[44px_44px] opacity-20 pointer-events-none" />
        <div className="container py-24 md:py-32 relative">
          <div className="max-w-3xl">
            <Badge className="mb-4 bg-indigo-600/20 text-indigo-300 border-indigo-500/30">New</Badge>
            <h1 className="text-4xl md:text-6xl font-semibold tracking-tight">
              Short links, <span className="text-transparent bg-clip-text bg-gradient-to-r from-indigo-400 to-purple-400">big impact</span>.
            </h1>
            <p className="mt-4 text-lg text-white/70">
              Create branded short URLs with analytics, expiry, QR codes, and AI-powered slugs. Built for speed and scale.
            </p>
            <div className="mt-8 flex flex-wrap gap-3">
              <Button asChild size="lg">
                <Link to="/register"><Rocket className="mr-2 h-5 w-5" /> Get started free</Link>
              </Button>
              <Button asChild variant="outline" size="lg" className="border-white/20 text-gray-900">
                <Link to="/pricing">See pricing</Link>
              </Button>
            </div>
            <div className="mt-6 flex items-center gap-4 text-sm text-white/60">
              <div className="flex items-center gap-2">
                <ShieldCheck className="h-4 w-4 text-green-400" /> Secure
              </div>
              <div className="flex items-center gap-2">
                <Gauge className="h-4 w-4 text-blue-400" /> Fast redirects
              </div>
              <div className="flex items-center gap-2">
                <QrCode className="h-4 w-4 text-purple-400" /> QR ready
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* Feature Cards */}
      <section className="container py-16 grid gap-6 md:grid-cols-3 pl-12">
        <Card className="bg-neutral-900 border-white/10">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-gray-100">
              <Wand2 className="h-5 w-5 text-indigo-400" /> AI-powered slugs
            </CardTitle>
          </CardHeader>
          <CardContent className="text-white/70">
            Get smart, human-readable slugs generated by AI. No more random strings.
          </CardContent>
        </Card>

        <Card className="bg-neutral-900 border-white/10">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-gray-100">
              <QrCode className="h-5 w-5 text-purple-400" /> QR codes
            </CardTitle>
          </CardHeader>
          <CardContent className="text-white/70">
            Every short link comes with a ready-to-share QR — great for offline.
          </CardContent>
        </Card>

        <Card className="bg-neutral-900 border-white/10">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-gray-100">
              <Gauge className="h-5 w-5 text-blue-400" /> Analytics & expiry
            </CardTitle>
          </CardHeader>
          <CardContent className="text-white/70">
            Track clicks by device/browser/country and set link expiry when needed.
          </CardContent>
        </Card>
      </section>

      {/* CTA */}
      <section className="container py-20 text-center">
        <h2 className="text-3xl md:text-4xl font-semibold">
          Ready to launch shorter, smarter links?
        </h2>
        <p className="mt-3 text-white/70">
          Join creators and teams using Linkly to share links that actually work for them.
        </p>
        <div className="mt-6">
          <Button asChild size="lg">
            <Link to="/register"><Sparkles className="mr-2 h-5 w-5" /> Create your first link</Link>
          </Button>
        </div>
      </section>
    </>
  );
}
