 {/* <section className="relative overflow-hidden p-12 pt-0">
        <div className="absolute inset-0 bg-grid bg-size-[44px_44px] opacity-20 pointer-events-none" />
        <div className="container py-24 md:py-32 relative">
          <div className="max-w-3xl">
            <Badge className="mb-4 bg-indigo-600/20 text-indigo-300 border-indigo-500/30">New</Badge>
            <h1 className="text-4xl md:text-6xl font-semibold tracking-tight">
              Short links, <span className="text-transparent bg-clip-text bg-linear-to-r from-indigo-400 to-purple-400">big impact</span>.
            </h1>
            <p className="mt-4 text-lg text-white/70">
              Create branded short URLs with analytics, expiry, QR codes, and AI-powered slugs. Built for speed and scale.
            </p>
            <div className="mt-8 flex flex-wrap gap-3">
              <Button asChild size="lg">
                <Link to="/register"><Rocket className="mr-2 h-5 w-5" /> Get started free</Link>
              </Button>
              <Button asChild variant="outline" size="lg" className="border-white/20 text-gray-900">
                <Link to="/pricing">See pricing</Link>
              </Button>
            </div>
            <div className="mt-6 flex items-center gap-4 text-sm text-white/60">
              <div className="flex items-center gap-2">
                <ShieldCheck className="h-4 w-4 text-green-400" /> Secure
              </div>
              <div className="flex items-center gap-2">
                <Gauge className="h-4 w-4 text-blue-400" /> Fast redirects
              </div>
              <div className="flex items-center gap-2">
                <QrCode className="h-4 w-4 text-purple-400" /> QR ready
              </div>
            </div>
          </div>
        </div>
      </section> */}
      
 
 {/* Feature Cards */}
      {/* <section className="container py-16 grid gap-6 md:grid-cols-3 pl-12">
        <Card className="bg-neutral-900 border-white/10">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-gray-100">
              <Wand2 className="h-5 w-5 text-indigo-400" /> AI-powered slugs
            </CardTitle>
          </CardHeader>
          <CardContent className="text-white/70">
            Get smart, human-readable slugs generated by AI. No more random strings.
          </CardContent>
        </Card>

        <Card className="bg-neutral-900 border-white/10">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-gray-100">
              <QrCode className="h-5 w-5 text-purple-400" /> QR codes
            </CardTitle>
          </CardHeader>
          <CardContent className="text-white/70">
            Every short link comes with a ready-to-share QR — great for offline.
          </CardContent>
        </Card>

        <Card className="bg-neutral-900 border-white/10">
          <CardHeader>
            <CardTitle className="flex items-center gap-2 text-gray-100">
              <Gauge className="h-5 w-5 text-blue-400" /> Analytics & expiry
            </CardTitle>
          </CardHeader>
          <CardContent className="text-white/70">
            Track clicks by device/browser/country and set link expiry when needed.
          </CardContent>
        </Card>
      </section> */}
      {/* <section className="container py-16 grid gap-8 md:grid-cols-3 max-w-fit bg-linear-to-b from-slate-700 to-slate-600/70">
          <div className="md:col-span-3 lg:col-span-3 px-6 md:px-0">
            <div className="mx-auto max-w-6xl">
              <h2 className="text-2xl md:text-3xl font-semibold text-white">Everything you need</h2>
              <p className="mt-2 text-white/70 max-w-2xl">Powerful features that make building and sharing short links effortless.</p>
            </div>
          </div>

          <article className="rounded-2xl bg-slate-900/60 border border-white/6 p-9 ml-10 shadow-md">
          <header className="flex items-start gap-3">
          <div className="inline-flex items-center justify-center h-10 w-10 rounded-lg bg-indigo-500/20">
          <svg className="h-5 w-5 text-indigo-300" viewBox="0 0 24 24" fill="none" aria-hidden>
          <path d="M3 21l18-9L3 3v7l12 2-12 2v7z" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
          </div>
          <h3 className="text-lg font-medium text-white">AI-powered slugs</h3>
          </header>
          <p className="mt-3 text-white/70">Get smart, human-readable slugs generated by AI. No more random strings — higher click-through and brand consistency.</p>
          </article>

          <article className="rounded-2xl bg-slate-900/60 border border-white/6 p-6 shadow-md">
          <header className="flex items-start gap-3">
          <div className="inline-flex items-center justify-center h-10 w-10 rounded-lg bg-purple-500/20">
          <svg className="h-5 w-5 text-purple-300" viewBox="0 0 24 24" fill="none" aria-hidden>
          <path d="M3 3h18v18H3z" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
          </div>
          <h3 className="text-lg font-medium text-white">QR codes</h3>
          </header>
          <p className="mt-3 text-white/70">Every short link comes with a ready-to-share QR — perfect for print, packaging, and offline campaigns.</p>
          </article>

          <article className="rounded-2xl bg-slate-900/60 border border-white/6 p-6 mr-10 shadow-md">
          <header className="flex items-start gap-3">
          <div className="inline-flex items-center justify-center h-10 w-10 rounded-lg bg-cyan-500/20">
          <svg className="h-5 w-5 text-cyan-300" viewBox="0 0 24 24" fill="none" aria-hidden>
          <path d="M3 12h18" stroke="currentColor" strokeWidth="1.2" strokeLinecap="round" strokeLinejoin="round" />
          </svg>
          </div>
          <h3 className="text-lg font-medium text-white">Analytics & expiry</h3>
          </header>
          <p className="mt-3 text-white/70">Track clicks by device, browser, and country — and schedule expirations when links are time-sensitive.</p>
          </article>
      </section> */}


      // import { Link } from "react-router-dom";
// import { Separator } from "@/components/ui/separator";

// export default function Footer() {
//   return (
//     <footer className="mt-16 border-t border-white/10 bg-neutral-950 ">
//       <div className="container py-12 grid gap-8 md:grid-cols-4 pl-42 ">
//         <div className="space-y-3 gap-12">
//           <div className="flex items-center gap-2">
//             <div className="h-7 w-7 rounded-lg bg-gradient-to-br from-indigo-500 to-purple-500" />
//             <span className="font-semibold">Linkly</span>
//           </div>
//           <p className="text-sm text-white/70">
//             Premium URL shortener with analytics, QR, expiry, and AI slugs.
//           </p>
//         </div>

//         <div>
//           <h4 className="mb-3 font-medium">Product</h4>
//           <ul className="space-y-2 text-sm text-white/70">
//             <li><Link to="/pricing" className="hover:text-white">Pricing</Link></li>
//             <li><Link to="/about" className="hover:text-white">About</Link></li>
//             <li><Link to="/contact" className="hover:text-white">Contact</Link></li>
//           </ul>
//         </div>

//         <div>
//           <h4 className="mb-3 font-medium">Resources</h4>
//           <ul className="space-y-2 text-sm text-white/70">
//             <li><a href="#" className="hover:text-white">Docs</a></li>
//             <li><a href="#" className="hover:text-white">API</a></li>
//             <li><a href="#" className="hover:text-white">Status</a></li>
//           </ul>
//         </div>

//         <div>
//           <h4 className="mb-3 font-medium">Legal</h4>
//           <ul className="space-y-2 text-sm text-white/70">
//             <li><a href="#" className="hover:text-white">Privacy</a></li>
//             <li><a href="#" className="hover:text-white">Terms</a></li>
//           </ul>
//         </div>
//       </div>
//       <Separator className="bg-white/10" />
//       <div className="container py-6 text-sm text-white/60 items-center justify-between">
//         © {new Date().getFullYear()} Linkly. All rights reserved.
//       </div>
//     </footer>
//   );
// }


/* eslint-disable no-unused-vars */
// import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
// import { Users, Rocket, Heart } from "lucide-react";

// export default function About() {
//   return (
//     <section className="container py-24 space-y-10">
//       <div className="max-w-3xl mx-auto text-center">
//         <h1 className="text-4xl md:text-5xl font-semibold mb-4">About Linkly</h1>
//         <p className="text-lg text-white/70">
//           We started Linkly with one idea: short links should be smart, secure,
//           and beautiful. Built with cutting-edge AI and privacy-first analytics,
//           Linkly helps thousands of creators and businesses share their world.
//         </p>
//       </div>

//       <div className="grid md:grid-cols-3 gap-6">
//         <Card className="bg-neutral-900 border-white/10">
//           <CardHeader>
//             <CardTitle className="flex items-center gap-2">
//               <Users className="h-5 w-5 text-indigo-400" /> Community First
//             </CardTitle>
//           </CardHeader>
//           <CardContent className="text-white/70">
//             Built with developers and marketers in mind — every feature was
//             requested by real users.
//           </CardContent>
//         </Card>

//         <Card className="bg-neutral-900 border-white/10">
//           <CardHeader>
//             <CardTitle className="flex items-center gap-2">
//               <Rocket className="h-5 w-5 text-purple-400" /> Lightning Fast
//             </CardTitle>
//           </CardHeader>
//           <CardContent className="text-white/70">
//             Optimized with Groq + Mongo + Vite — sub-millisecond redirects and
//             analytics that never slow you down.
//           </CardContent>
//         </Card>

//         <Card className="bg-neutral-900 border-white/10">
//           <CardHeader>
//             <CardTitle className="flex items-center gap-2">
//               <Heart className="h-5 w-5 text-pink-400" /> Built with Love
//             </CardTitle>
//           </CardHeader>
//           <CardContent className="text-white/70">
//             We obsess over details, polish every pixel, and write code we’re
//             proud of. That’s Linkly.
//           </CardContent>
//         </Card>
//       </div>
//     </section>
//   );
// }


// import React from "react";
// import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
// import { Users, Rocket, Heart } from "lucide-react";

// export default function About() {
//   return (
//     <section className="bg-slate-900 py-16">
//       <div className="container mx-auto px-4">
//         <div className="max-w-2xl mx-auto text-center">
//           <h1 className="text-3xl sm:text-4xl font-semibold text-white">About Linkly</h1>
//           <p className="mt-3 text-sm sm:text-base text-white/70">Linkly makes short links smart, secure, and beautiful — trusted by creators and teams.</p>
//         </div>

//         <div className="mt-10 grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
//           <Card className="bg-neutral-800 border-transparent">
//             <CardHeader>
//               <CardTitle className="flex items-center gap-3">
//                 <div className="inline-flex items-center justify-center h-9 w-9 rounded-lg bg-indigo-600/20 text-indigo-300">
//                   <Users className="h-4 w-4" />
//                 </div>
//                 <span className="text-white">Community First</span>
//               </CardTitle>
//             </CardHeader>
//             <CardContent className="text-white/70 text-sm">Features shaped by real users — built for developers and marketers.</CardContent>
//           </Card>

//           <Card className="bg-neutral-800 border-transparent">
//             <CardHeader>
//               <CardTitle className="flex items-center gap-3">
//                 <div className="inline-flex items-center justify-center h-9 w-9 rounded-lg bg-purple-600/20 text-purple-300">
//                   <Rocket className="h-4 w-4" />
//                 </div>
//                 <span className="text-white">Lightning Fast</span>
//               </CardTitle>
//             </CardHeader>
//             <CardContent className="text-white/70 text-sm">Optimized for speed — instant redirects and lightweight analytics.</CardContent>
//           </Card>

//           <Card className="bg-neutral-800 border-transparent">
//             <CardHeader>
//               <CardTitle className="flex items-center gap-3">
//                 <div className="inline-flex items-center justify-center h-9 w-9 rounded-lg bg-pink-600/20 text-pink-300">
//                   <Heart className="h-4 w-4" />
//                 </div>
//                 <span className="text-white">Built with Love</span>
//               </CardTitle>
//             </CardHeader>
//             <CardContent className="text-white/70 text-sm">Attention to detail, clean design, and code we’re proud to ship.</CardContent>
//           </Card>
//         </div>
//       </div>
//     </section>
//   );
// }


// import { useEffect, useState } from "react";
// import axiosClient from "@/api/axiosClient";
// import { Button } from "@/components/ui/button";
// import { Check } from "lucide-react";
// import { toast } from "sonner";

// export default function Pricing() {
//   const [user, setUser] = useState(null);
//   const plans = [
//     {
//       name: "Free",
//       price: "₹0",
//       credits: 5,
//       features: [
//         "5 short links",
//         "Basic analytics",
//         "QR code support",
//         "Community email support"
//       ],
//       planKey: "free",
//     },
//     {
//       name: "Pro",
//       price: "₹99",
//       credits: 50,
//       features: [
//         "50 short links",
//         "Advanced analytics",
//         "Custom expiry",
//         "No ads + Faster redirects"
//       ],
//       planKey: "pro",
//     },
//     {
//       name: "Business",
//       price: "₹299",
//       credits: 250,
//       features: [
//         "250 short links",
//         "Team access + RBAC",
//         "Webhook/API Access",
//         "Priority support"
//       ],
//       planKey: "business",
//     },
//   ];

//   useEffect(() => {
//     axiosClient.get("/api/auth/me", { withCredentials: true })
//       .then((res) => setUser(res.data.user))
//       .catch(() => {});
//   }, []);

//   const handlePayment = async (plan) => {
//     try {
//       const res = await axiosClient.post("/api/payment/create-order", { plan }, { withCredentials: true });

//       const options = {
//         key: import.meta.env.VITE_RAZORPAY_KEY_ID,
//         amount: res.data.amount,
//         currency: "INR",
//         name: "Linkly",
//         description: `${plan.name} Plan Subscription`,
//         order_id: res.data.orderId,
//         handler: async (response) => {
//           await axiosClient.post("/api/payment/verify", response, { withCredentials: true });
//           toast.success("Payment successful! Plan upgraded.");
//           setTimeout(() => window.location.reload(), 1000);
//         },
//         prefill: {
//           name: user?.name || "",
//           email: user?.email || "",
//         },
//         theme: { color: "#6366f1" },
//       };

//       const razor = new window.Razorpay(options);
//       razor.open();
//     } catch (err) {
//       console.error(err);
//       toast.error("Payment failed");
//     }
//   };

//   return (
//     <section className="container py-12">
//       <h1 className="text-3xl font-bold text-center mb-8">Choose Your Plan</h1>

//       {/* My Subscription Section */}
//       {user && (
//         <div className="text-center mb-10">
//           <p className="text-white/70">
//             Current Plan: <span className="font-semibold">{user.plan?.toUpperCase()}</span>
//           </p>
//           <p className="text-white/70">
//             Available Credits: <span className="text-indigo-400">{user.credits}</span>
//           </p>
//         </div>
//       )}

//       <div className="grid md:grid-cols-3 gap-6">
//         {plans.map((plan) => (
//           <div
//             key={plan.name}
//             className="bg-neutral-900 border border-white/10 rounded-xl p-6 hover:border-indigo-500 transition"
//           >
//             <h2 className="text-xl font-semibold mb-2">{plan.name}</h2>
//             <p className="text-3xl font-bold mb-4">{plan.price}</p>
//             <ul className="space-y-2 mb-6">
//               {plan.features.map((feature, i) => (
//                 <li key={i} className="flex items-center gap-2 text-white/70">
//                   <Check className="h-4 w-4 text-green-400" /> {feature}
//                 </li>
//               ))}
//             </ul>

//             {user?.plan === plan.planKey ? (
//               <Button disabled className="w-full">Your Current Plan</Button>
//             ) : (
//               <Button
//                 className="w-full"
//                 onClick={() => handlePayment(plan)}
//               >
//                 {plan.price === "₹0" ? "Start Free" : "Upgrade"}
//               </Button>
//             )}
//           </div>
//         ))}
//       </div>
//     </section>
//   );
// }



import React, { useEffect, useRef, useState } from "react";
import { Menu, X } from "lucide-react";
import { NavLink, Link, useNavigate } from "react-router-dom";
import { useAuth } from "@/context/AuthContext";
import {
  Avatar,
  AvatarImage,
  AvatarFallback,
} from "@/components/ui/avatar";

const NAV_LINKS = [
  { to: "/", label: "Home" },
  { to: "/about", label: "About" },
  { to: "/pricing", label: "Pricing" },
  { to: "/contact", label: "Contact" },
];

function UserMenu({ user, initials, onLogout }) {
  const [open, setOpen] = useState(false);
  const menuRef = useRef(null);
  const btnRef = useRef(null);

  useEffect(() => {
    function handleDocClick(e) {
      if (!menuRef.current) return;
      if (
        !menuRef.current.contains(e.target) &&
        !btnRef.current.contains(e.target)
      ) {
        setOpen(false);
      }
    }
    function handleEsc(e) {
      if (e.key === "Escape") setOpen(false);
    }
    document.addEventListener("mousedown", handleDocClick);
    document.addEventListener("keydown", handleEsc);
    return () => {
      document.removeEventListener("mousedown", handleDocClick);
      document.removeEventListener("keydown", handleEsc);
    };
  }, []);

  return (
    <div className="relative">
      <button
        ref={btnRef}
        onClick={() => setOpen((s) => !s)}
        className="flex items-center gap-3 rounded-md px-2 py-1 hover:bg-white/5 transition"
        aria-expanded={open}
        aria-haspopup="true"
      >
        <Avatar className="h-8 w-8">
          <AvatarImage src={user.avatarUrl || ""} />
          <AvatarFallback>{initials}</AvatarFallback>
        </Avatar>
        <div className="hidden sm:flex flex-col items-start leading-tight">
          <span className="text-sm text-white">{user.name}</span>
          <span className="text-xs text-white/60 capitalize">
            {user.role} • {user.plan}
          </span>
        </div>
        <svg
          className={`h-4 w-4 text-white/60 transition-transform ${open ? "rotate-180" : ""
            }`}
          viewBox="0 0 20 20"
          fill="none"
          aria-hidden
        >
          <path d="M6 8l4 4 4-4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
        </svg>
      </button>

      <div
        ref={menuRef}
        className={`origin-top-right absolute right-0 mt-3 w-64 rounded-lg bg-slate-900/95 border border-white/6 backdrop-blur-md p-3 shadow-2xl ring-1 ring-black/10 transform transition-all duration-150 ${open ? "opacity-100 scale-100 visible" : "opacity-0 scale-95 invisible pointer-events-none"
          }`}
      >
        <div className="flex items-center gap-3 px-1 py-2">
          <Avatar className="h-10 w-10">
            <AvatarImage src={user.avatarUrl || ""} />
            <AvatarFallback>{initials}</AvatarFallback>
          </Avatar>
          <div className="flex-1 min-w-0">
            <p className="text-sm font-medium text-white truncate">{user.name}</p>
            <p className="text-xs text-white/60 truncate">{user.email}</p>
          </div>
        </div>

        <div className="my-2 h-px bg-white/6" />

        <div className="px-2 text-xs text-white/70 flex items-center justify-between">
          <div>Credits</div>
          <div className="font-medium text-indigo-300">{user.credits}</div>
        </div>

        <div className="my-2 h-px bg-white/6" />

        <nav className="flex flex-col gap-2 px-2">
          <Link to="/profile" onClick={() => setOpen(false)} className="rounded-md px-3 py-2 text-sm text-white/80 hover:bg-white/4 transition">Profile</Link>
          <Link to="/dashboard" onClick={() => setOpen(false)} className="rounded-md px-3 py-2 text-sm text-white/80 hover:bg-white/4 transition">Dashboard</Link>
          {user.role === "admin" && (
            <Link to="/admin" onClick={() => setOpen(false)} className="rounded-md px-3 py-2 text-sm text-white/80 hover:bg-white/4 transition">Admin Panel</Link>
          )}
          <Link to="/pricing" onClick={() => setOpen(false)} className="rounded-md px-3 py-2 text-sm text-white/80 hover:bg-white/4 transition">Pricing / Upgrade</Link>
        </nav>

        <div className="my-3 h-px bg-white/6" />

        <div className="px-2">
          <button
            onClick={() => { setOpen(false); onLogout(); }}
            className="w-full rounded-md py-2 text-sm text-red-400 hover:bg-red-500/6 transition"
          >
            Logout
          </button>
        </div>
      </div>
    </div>
  );
}

export default function Header() {
  const [isOpen, setIsOpen] = useState(false);
  const [scrolled, setScrolled] = useState(false);
  const navigate = useNavigate();
  const { user, logout } = useAuth();

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 50);
    window.addEventListener("scroll", onScroll);
    return () => window.removeEventListener("scroll", onScroll);
  }, []);

  const initials = (user?.name || "U")
    .split(" ")
    .map((w) => w[0]?.toUpperCase())
    .join("");

  const handleLogout = async () => {
    try {
      await logout();
      navigate("/");
    } catch (err) {
      console.error("Logout failed:", err);
    }
  };

  return (
    <header className={`fixed inset-x-0 top-5 z-50 px-4 sm:px-6 lg:px-8 transition-all duration-300 ${scrolled ? "backdrop-blur-xl bg-slate-900/60 shadow-lg" : "bg-transparent"}`}>
      <div className="max-w-6xl mx-auto">
        <nav className="relative flex items-center justify-between rounded-2xl px-4 py-3">
          {/* Brand */}
          <Link to="/" className="inline-flex items-center gap-3">
            <div className="h-9 w-9 rounded-lg bg-linear-to-br from-indigo-500 to-purple-500 shadow" />
            <span className="text-lg font-semibold text-white">Linkly</span>
          </Link>

          {/* Desktop nav */}
          <div className="hidden md:flex items-center gap-8">
            <div className="flex items-center gap-6">
              {NAV_LINKS.map((l) => (
                <NavLink
                  key={l.to}
                  to={l.to}
                  className={({ isActive }) => `relative text-sm font-medium transition-colors ${isActive ? "text-white" : "text-white/80 hover:text-white"}`}
                >
                  {l.label}
                </NavLink>
              ))}
            </div>
          </div>

          {/* Right side */}
          <div className="flex items-center gap-3">
            {/* Desktop auth buttons */}
            <div className="hidden md:flex items-center gap-3">
              {user ? (
                <>
                  <Link to="/dashboard" className="inline-flex items-center rounded-md px-3 py-1 text-sm font-medium bg-white/6 hover:bg-white/8 transition">
                    Dashboard
                  </Link>
                  <UserMenu user={user} initials={initials} onLogout={handleLogout} />
                </>
              ) : (
                <>
                  <Link to="/login" className="text-sm font-medium text-white/80 hover:text-white transition">Login</Link>
                  <Link to="/register" className="inline-flex items-center rounded-md px-3 py-1 bg-linear-to-br from-indigo-500 to-purple-500 text-white text-sm font-semibold shadow hover:brightness-105 transition">Get Started</Link>
                </>
              )}
            </div>

            {/* Mobile toggle */}
            <button
              onClick={() => setIsOpen((s) => !s)}
              className="inline-flex items-center justify-center rounded-md p-2 text-cyan-400 md:hidden"
              aria-expanded={isOpen}
              aria-label="Toggle navigation"
            >
              {isOpen ? <X size={20} /> : <Menu size={20} />}
            </button>
          </div>

          {/* Mobile menu */}
          <div className={`absolute left-4 right-4 top-full mt-3 md:hidden transition-all duration-200 ${isOpen ? "opacity-100 visible" : "opacity-0 invisible pointer-events-none"}`}>
            <div className="rounded-2xl bg-slate-900/95 border border-white/6 p-4 shadow-lg">
              <div className="flex flex-col gap-3">
                {NAV_LINKS.map((l) => (
                  <NavLink
                    key={l.to}
                    to={l.to}
                    onClick={() => setIsOpen(false)}
                    className={({ isActive }) => `block text-left text-sm font-medium px-2 py-2 rounded-md transition-colors ${isActive ? "text-white" : "text-white/80 hover:text-white"}`}
                  >
                    {l.label}
                  </NavLink>
                ))}

                <div className="border-t border-white/6 my-2" />

                {user ? (
                  <>
                    <div className="text-sm text-white/70">Credits: <span className="text-indigo-300">{user.credits}</span></div>

                    <Link to="/dashboard" onClick={() => setIsOpen(false)} className="w-full">
                      <button className="w-full mt-2 rounded-md px-3 py-2 bg-white/6 hover:bg-white/8 transition text-sm">Dashboard</button>
                    </Link>

                    <Link to="/profile" onClick={() => setIsOpen(false)} className="w-full">
                      <button className="w-full mt-2 rounded-md px-3 py-2 border border-white/6 hover:bg-white/4 transition text-sm">Profile</button>
                    </Link>

                    {user.role === "admin" && (
                      <Link to="/admin" onClick={() => setIsOpen(false)} className="w-full">
                        <button className="w-full mt-2 rounded-md px-3 py-2 bg-transparent hover:bg-white/4 transition text-sm">Admin Panel</button>
                      </Link>
                    )}

                    <button onClick={() => { handleLogout(); setIsOpen(false); }} className="w-full mt-2 rounded-md px-3 py-2 text-sm text-red-400 hover:bg-red-500/6 transition">
                      Logout
                    </button>
                  </>
                ) : (
                  <>
                    <Link to="/login" onClick={() => setIsOpen(false)} className="w-full">
                      <button className="w-full mt-2 rounded-md px-3 py-2 text-sm text-white/80 hover:text-white transition">Login</button>
                    </Link>

                    <Link to="/register" onClick={() => setIsOpen(false)} className="w-full">
                      <button className="w-full mt-2 rounded-md px-3 py-2 bg-linear-to-br from-indigo-500 to-purple-500 text-white font-semibold hover:brightness-105 transition">Get Started</button>
                    </Link>
                  </>
                )}
              </div>
            </div>
          </div>
        </nav>
      </div>
    </header>
  );
}





// import React from "react";
// import { useState, useEffect } from "react";
// import { Menu, X } from "lucide-react";
// import {NavLink,Link, useNavigate} from 'react-router'
// import { useAuth } from "@/context/AuthContext";
// // import { Button } from "@/components/ui/button";
// import {
//   Avatar,
//   AvatarImage,
//   AvatarFallback
// } from "@/components/ui/avatar";
// import {
//   DropdownMenu,
//   DropdownMenuTrigger,
//   DropdownMenuContent,
//   DropdownMenuItem,
//   DropdownMenuSeparator,
//   DropdownMenuLabel
// } from "@/components/ui/dropdown-menu";

// const Header = () => {
//   const [isOpen, setIsOpen] = useState(false);
//   const [scrolled, setScrolled] = useState(false);

//    const navigate = useNavigate();
//   const { user, logout } = useAuth(); 

//   const initials = (user?.name || "U")
//     .split(" ")
//     .map((w) => w[0]?.toUpperCase())
//     .join("");


//    const handleLogout = async () => {
//     try {
//       await logout();
//       navigate("/");
//     } catch (err) {
//       console.error("Logout failed:", err);
//     }
//   };

//   useEffect(() => {
//     const handleScroll = () => setScrolled(window.scrollY > 50);
//     window.addEventListener('scroll', handleScroll);
//     return () => window.removeEventListener('scroll', handleScroll);
//   }, []);

//   const navLinks = ['Home', 'About', 'Pricing', 'Contact'];

//   return (
//     <header className={`fixed top-0 w-3/4 z-50 transition-all duration-500 left-1/2 -translate-x-1/2 mt-5 rounded-3xl ${scrolled ? 'bg-gray-500/60 backdrop-blur-xl shadow-lg shadow-cyan-500/10' : 'bg-transparent'}`}>
//       <nav className="container mx-auto px-6 py-4">
//         <div className="flex items-center justify-between">
//           <div className="text-2xl font-bold bg-linear-to-r from-cyan-400 to-purple-500 bg-clip-text text-transparent">
//             Linkly
//           </div>
          
//           <div className="hidden md:flex space-x-8">
//             {navLinks.map(link => (
//               <NavLink
//                 key={link}
//                 to={`/${link.toLowerCase()}`}
//                 className="text-gray-100 hover:text-cyan-400 transition-colors duration-300 relative group"
//               >
//                 {link}
//                 <span className="absolute -bottom-1 left-0 w-0 h-0.5 bg-linear-to-r from-cyan-400 to-purple-500 group-hover:w-full transition-all duration-300" />
//               </NavLink>
//             ))}
//             <div className="flex items-center gap-3">
//               {/* Desktop auth */}
//               <div className="hidden md:flex items-center gap-3">
//                 {user ? (
//                   <>
//                     <button variant="ghost" asChild>
//                       <Link to="/dashboard">Dashboard</Link>
//                     </button>

//                     <DropdownMenu>
//                       <DropdownMenuTrigger asChild>
//                         <button className="flex items-center gap-3 rounded-md px-2 py-1 hover:bg-white/5 transition">
//                           <Avatar className="h-8 w-8">
//                             <AvatarImage src={user.avatarUrl || ""} />
//                             <AvatarFallback>{initials}</AvatarFallback>
//                           </Avatar>
//                           <div className="hidden sm:flex flex-col items-start leading-tight">
//                             <span className="text-sm text-white">{user.name}</span>
//                             <span className="text-xs text-white/60 capitalize">
//                               {user.role} • {user.plan}
//                             </span>
//                           </div>
//                         </button>
//                       </DropdownMenuTrigger>

//                       <DropdownMenuContent align="end" className="w-56">
//                         <DropdownMenuLabel>
//                           <div className="flex items-center gap-3">
//                             <Avatar className="h-8 w-8">
//                               <AvatarImage src={user.avatarUrl || ""} />
//                               <AvatarFallback>{initials}</AvatarFallback>
//                             </Avatar>
//                             <div>
//                               <p className="text-sm font-medium">{user.name}</p>
//                               <p className="text-xs text-white/60">{user.email}</p>
//                             </div>
//                           </div>
//                         </DropdownMenuLabel>

//                         <DropdownMenuSeparator />

//                         <div className="px-3 py-2 text-xs text-white/70">
//                           Credits: <span className="text-indigo-400">{user.credits}</span>
//                         </div>

//                         <DropdownMenuSeparator />

//                         <DropdownMenuItem asChild>
//                           <Link to="/profile">Profile</Link>
//                         </DropdownMenuItem>
//                         <DropdownMenuItem asChild>
//                           <Link to="/dashboard">Dashboard</Link>
//                         </DropdownMenuItem>
//                         {user.role === "admin" && (
//                           <DropdownMenuItem asChild>
//                             <Link to="/admin">Admin Panel</Link>
//                           </DropdownMenuItem>
//                         )}

//                         <DropdownMenuSeparator />

//                         <DropdownMenuItem onClick={handleLogout} className="text-red-400">
//                           Logout
//                         </DropdownMenuItem>
//                       </DropdownMenuContent>
//                     </DropdownMenu>
//                   </>
//                 ) : (
//                   <>
//                     <button variant="ghost" asChild>
//                       <Link to="/login">Login</Link>
//                     </button>
//                     <button asChild>
//                       <Link to="/register">Get Started</Link>
//                     </button>
//                   </>
//                 )}
//               </div>

//               {/* Mobile toggle */}
//               <button
//                 onClick={() => setIsOpen((s) => !s)}
//                 className="inline-flex items-center justify-center rounded-md p-2 text-cyan-400 md:hidden"
//                 aria-expanded={isOpen}
//                 aria-label="Toggle navigation"
//               >
//                 {isOpen ? <X size={20} /> : <Menu size={20} />}
//               </button>
//             </div>
//           </div>
          

//           <button onClick={() => setIsOpen(!isOpen)} className="md:hidden text-cyan-400">
//             {isOpen ? <X size={24} /> : <Menu size={24} />}
//           </button>
//         </div>

//         {isOpen && (
//           <div className="md:hidden mt-4 space-y-4 animate-fadeIn ">
//             {navLinks.map(link => (
//               <NavLink
//                 key={link}
//                 to={`/${link.toLowerCase()}`}
//                 onClick={() => setIsOpen(false)}
//                 className="block text-gray-200 hover:text-cyan-400 transition-colors text-right"
//               >
//                 {link}
//               </NavLink>

//             ))}
//             <div className="border-t border-white/6 my-2" />
//              {user ? (
//                   <>
//                     <div className="text-sm text-white/70 text-right">
//                       Credits: <span className="text-indigo-300">{user.credits}</span>
//                     </div>

//                     <Link to="/dashboard" onClick={() => setIsOpen(false)}>
//                       <button className="w-full mt-2">Dashboard</button>
//                     </Link>

//                     <Link to="/profile" onClick={() => setIsOpen(false)}>
//                       <button variant="outline" className="w-full mt-2">Profile</button>
//                     </Link>

//                     {user.role === "admin" && (
//                       <Link to="/admin" onClick={() => setIsOpen(false)}>
//                         <button variant="ghost" className="w-full mt-2">Admin Panel</button>
//                       </Link>
//                     )}

//                     <button variant="destructive" onClick={() => { handleLogout(); setIsOpen(false); }} className="w-full mt-2">
//                       Logout
//                     </button>
//                   </>
//                 ) : (
//                   <>
//                     <Link to="/login" onClick={() => setIsOpen(false)}>
//                       <button variant="ghost" className="w-full">Login</button>
//                     </Link>
//                     <Link to="/register" onClick={() => setIsOpen(false)}>
//                       <button className="w-full mt-2">Get Started</button>
//                     </Link>
//                   </>
//                 )}
//           </div>
//         )}
//       </nav>
//     </header>
//   );
// };

// export default Header;





// import { useEffect, useState } from "react";
// import axiosClient from "@/api/axiosClient";
// import { Button } from "@/components/ui/button";
// import { Input } from "@/components/ui/input";
// import { toast } from "sonner";
// import { useNavigate } from "react-router-dom";

// export default function Profile() {
//   const [user, setUser] = useState(null);
//   const [totalUrls, setTotalUrls] = useState(0);
//   const [editing, setEditing] = useState(false);
//   const [updatedName, setUpdatedName] = useState("");
//   const [passwords, setPasswords] = useState({ oldPassword: "", newPassword: "" });
//   const [loading, setLoading] = useState(false);
//   const navigate = useNavigate();

//   // Fetch user details + total links
//   useEffect(() => {
//     axiosClient
//       .get("/api/auth/me", { withCredentials: true })
//       .then((res) => {
//         setUser(res.data.user);
//         setUpdatedName(res.data.user?.name || "");
//       })
//       .catch(() => {});

//     axiosClient
//       .post("/api/user/urls", {}, { withCredentials: true })
//       .then((res) => {
//         setTotalUrls(res.data.urls?.length || 0);
//       })
//       .catch(() => setTotalUrls(0));
//   }, []);

//   // Update name
//   const handleNameUpdate = async () => {
//     if (!updatedName.trim()) return toast.error("Name cannot be empty");

//     setLoading(true);
//     try {
//       await axiosClient.put("/api/auth/update-name", { name: updatedName }, { withCredentials: true });
//       toast.success("Name updated");
//       setUser((prev) => ({ ...prev, name: updatedName }));
//       setEditing(false);
//     } catch {
//       toast.error("Failed to update name");
//     } finally {
//       setLoading(false);
//     }
//   };

//   // Change password
//   const handlePasswordChange = async () => {
//     if (!passwords.oldPassword || !passwords.newPassword) {
//       return toast.error("Please fill both password fields");
//     }

//     try {
//       await axiosClient.put("/api/auth/change-password", passwords, { withCredentials: true });
//       toast.success("Password updated. Please Login again");
//       setPasswords({ oldPassword: "", newPassword: "" });
//       setTimeout(()=>{
//         window.location.href = "/login";
//       }, 1000);
//     } catch (error) {
//       toast.error(error.response?.data?.message || "Failed to update password");
//     }
//   };

//   // Delete account
//   const handleDeleteAccount = async () => {
//     if (!confirm("Are you sure you want to delete your account? This action cannot be undone.")) return;

//     try {
//       await axiosClient.delete("/api/auth/delete-account", { withCredentials: true });
//       toast.success("Account deleted");
//       navigate("/");
//     } catch {
//       toast.error("Couldn't delete account");
//     }
//   };

//   if (!user) return <p className="text-center mt-10 text-white">Loading...</p>;

//   return (
//     <div className="container py-10">
//       <h1 className="text-3xl font-semibold mb-6">My Profile</h1>

//       {/* User Info */}
//       <div className="bg-neutral-900 p-5 rounded-lg border border-white/10 mb-6">
//         <p><strong>Name:</strong> {user.name}</p>
//         <p><strong>Email:</strong> {user.email}</p>
//         <p><strong>Role:</strong> {user.role}</p>
//         <p><strong>Member Since:</strong> {new Date(user.createdAt).toLocaleDateString()}</p>
//         <p><strong>Total Links Created:</strong> {totalUrls}</p>

//         {editing ? (
//           <div className="mt-4 flex items-center gap-2">
//             <Input
//               value={updatedName}
//               onChange={(e) => setUpdatedName(e.target.value)}
//               className="bg-neutral-800 border-white/20 text-white"
//             />
//             <Button onClick={handleNameUpdate} disabled={loading}>Save</Button>
//             <Button variant="ghost" onClick={() => setEditing(false)}>Cancel</Button>
//           </div>
//         ) : (
//           <Button className="mt-4" onClick={() => setEditing(true)}>Edit Name</Button>
//         )}
//       </div>

//       {/* Change Password */}
//       <div className="bg-neutral-900 p-5 rounded-lg border border-white/10 mb-6">
//         <h2 className="text-xl font-semibold mb-4">Change Password</h2>
//         <div className="flex flex-col gap-3">
//           <Input
//             type="password"
//             placeholder="Old Password"
//             value={passwords.oldPassword}
//             onChange={(e) => setPasswords({ ...passwords, oldPassword: e.target.value })}
//             className="bg-neutral-800 border-white/20"
//           />
//           <Input
//             type="password"
//             placeholder="New Password"
//             value={passwords.newPassword}
//             onChange={(e) => setPasswords({ ...passwords, newPassword: e.target.value })}
//             className="bg-neutral-800 border-white/20"
//           />
//           <Button onClick={handlePasswordChange}>Update Password</Button>
//         </div>
//       </div>

//       {/* Danger Zone */}
//       <div className="bg-neutral-900 p-5 rounded-lg border border-red-400/40">
//         <h2 className="text-xl font-semibold text-red-400 mb-2">Danger Zone</h2>
//         <p className="text-sm text-white/70 mb-4">Deleting your account will remove all your data permanently.</p>
//         <Button variant="destructive" onClick={handleDeleteAccount}>Delete My Account</Button>
//       </div>
//     </div>
//   );
// }





// import { useEffect, useState } from "react";
// import axiosClient from "@/api/axiosClient";
// import { Button } from "@/components/ui/button";
// import { Link, useNavigate } from "react-router-dom";
// import { Copy, Trash2, BarChart3, QrCode, ArrowUpRight } from "lucide-react";
// import { toast } from "sonner";
// import { Input } from "@/components/ui/input";
// import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
// import QRCodeModal from "@/components/common/QRCodeModal";

// export default function Dashboard() {
//   const [user, setUser] = useState(null);
//   const [urls, setUrls] = useState([]);
//   const [loading, setLoading] = useState(true);
//   const [search, setSearch] = useState("");
//   const [qrOpen, setQrOpen] = useState(false);
//   const [selectedSlug, setSelectedSlug] = useState("");

//   const navigate = useNavigate();
//   const appUrl = import.meta.env.VITE_APP_URL || "http://localhost:3000/";

//   const fetchMe = async () => {
//     try {
//       const res = await axiosClient.get("/api/auth/me", { withCredentials: true });
//       setUser(res.data.user);
//     } catch {
//       setUser(null);
//     }
//   };

//   const fetchUrls = async () => {
//     try {
//       const res = await axiosClient.post("/api/user/urls", {}, { withCredentials: true });
//       setUrls(res.data.urls || []);
//     } catch (error) {
//       console.error("Error loading URLs:", error);
//       toast.error("Failed to load URLs");
//     } finally {
//       setLoading(false);
//     }
//   };

//   useEffect(() => {
//     fetchMe();
//     fetchUrls();
//   }, []);

//   const deleteUrl = async (id) => {
//     if (!confirm("Are you sure you want to delete this URL?")) return;
//     try {
//       await axiosClient.delete(`/api/user/url/${id}`, { withCredentials: true });
//       toast.success("URL deleted");
//       fetchUrls();
//       fetchMe();
//     } catch {
//       toast.error("Delete failed");
//     }
//   };

//   const filteredUrls = urls.filter((u) =>
//     (u.full_url || "").toLowerCase().includes(search.toLowerCase()) ||
//     (u.short_url || "").toLowerCase().includes(search.toLowerCase())
//   );

//   const StatCard = ({ title, value, cta }) => (
//     <Card className="bg-neutral-900 border-white/10">
//       <CardHeader className="pb-2">
//         <CardTitle className="text-sm text-white/70">{title}</CardTitle>
//       </CardHeader>
//       <CardContent className="flex items-end justify-between">
//         <div className="text-3xl font-semibold">{value}</div>
//         {cta}
//       </CardContent>
//     </Card>
//   );

//   return (
//     <div className="container py-10">
//       <div className="flex items-center justify-between mb-6">
//         <h1 className="text-3xl font-semibold">My Links</h1>
//         <Button asChild>
//           <Link to="/create">+ Create New</Link>
//         </Button>
//       </div>

//       {/* Stats Section */}
//       <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-6">
//         <StatCard
//           title="Available Credits"
//           value={user?.credits ?? "—"}
//           cta={
//             (user?.credits ?? 0) <= 0 && (
//               <Button size="sm" variant="outline" onClick={() => navigate("/pricing")}>
//                 Upgrade <ArrowUpRight className="ml-1 h-4 w-4" />
//               </Button>
//             )
//           }
//         />
//         <StatCard
//           title="Current Plan"
//           value={(user?.plan || "free").toUpperCase()}
//           cta={
//             (user?.plan || "free") === "free" && (
//               <Button size="sm" variant="outline" onClick={() => navigate("/pricing")}>
//                 Upgrade <ArrowUpRight className="ml-1 h-4 w-4" />
//               </Button>
//             )
//           }
//         />
//         <StatCard title="Total Links" value={urls.length} />
//       </div>

//       {/* Search */}
//       <Input
//         placeholder="Search your links…"
//         className="mb-4 bg-neutral-800 border-white/20"
//         value={search}
//         onChange={(e) => setSearch(e.target.value)}
//       />

//       {/* Table */}
//       {loading ? (
//         <div className="space-y-3">
//           {[1, 2, 3].map((i) => (
//             <div key={i} className="h-12 w-full bg-neutral-300/50 rounded-md animate-pulse"></div>
//           ))}
//         </div>
//       ) : filteredUrls.length === 0 ? (
//         <Card className="bg-neutral-900 border-white/10">
//           <CardContent className="py-10 text-center text-white/60">
//             No URLs found. Create your first one!
//           </CardContent>
//         </Card>
//       ) : (
//         <div className="overflow-auto border border-white/10 rounded-lg">
//           <table className="w-full text-left text-white/80">
//             <thead className="bg-neutral-900 text-white/60">
//               <tr>
//                 <th className="p-3">Slug</th>
//                 <th className="p-3">Original URL</th>
//                 <th className="p-3 text-center">Clicks</th>
//                 <th className="p-3 text-center">Actions</th>
//               </tr>
//             </thead>
//             <tbody>
//               {filteredUrls.map((url) => {
//                 const fullShortUrl = url.short_url?.startsWith("http")
//                   ? url.short_url
//                   : `${appUrl.replace(/\/+$/, "")}/${(url.short_url || "").replace(/^\/+/, "")}`;

//                 const slug = fullShortUrl.replace(appUrl.replace(/\/+$/, "") + "/", "");

//                 return (
//                   <tr key={url._id} className="border-t border-white/10">
//                     <td className="p-3 text-indigo-400">
//                       <a href={fullShortUrl} target="_blank" rel="noreferrer" className="hover:underline">
//                         {slug}
//                       </a>
//                     </td>
//                     <td className="p-3 max-w-xs truncate">{url.full_url}</td>
//                     <td className="p-3 text-center">{url.clicks}</td>
//                     <td className="p-3 text-center flex justify-center gap-2">
//                       <Button
//                         size="icon"
//                         variant="ghost"
//                         onClick={() => {
//                           navigator.clipboard.writeText(fullShortUrl);
//                           toast.success("Copied to clipboard");
//                         }}
//                       >
//                         <Copy className="h-4 w-4" />
//                       </Button>

//                       <Button
//                         size="icon"
//                         variant="ghost"
//                         onClick={() => {
//                           setSelectedSlug(slug);
//                           setQrOpen(true);
//                         }}
//                       >
//                         <QrCode className="h-4 w-4" />
//                       </Button>

//                       <Button size="icon" variant="ghost" asChild>
//                         <Link to={`/analytics/${slug}`}>
//                           <BarChart3 className="h-4 w-4" />
//                         </Link>
//                       </Button>

//                       <Button
//                         size="icon"
//                         variant="ghost"
//                         className="text-red-400 hover:text-red-500"
//                         onClick={() => deleteUrl(url._id)}
//                       >
//                         <Trash2 className="h-4 w-4" />
//                       </Button>
//                     </td>
//                   </tr>
//                 );
//               })}
//             </tbody>
//           </table>
//         </div>
//       )}

//       {/* QR Modal */}
//       <QRCodeModal open={qrOpen} onClose={() => setQrOpen(false)} slug={selectedSlug} />
//     </div>
//   );
// }




// import { Input } from "@/components/ui/input";
// import { Textarea } from "@/components/ui/textarea";
// import { Button } from "@/components/ui/button";
// import { Mail, Phone, MapPin } from "lucide-react";

// export default function Contact() {
//   return (
//     <section className="container py-24">
//       <div className="max-w-2xl mx-auto text-center mb-10">
//         <h1 className="text-4xl md:text-5xl font-semibold mb-4">
//           Get in touch
//         </h1>
//         <p className="text-white/70 text-lg">
//           Have a question or partnership idea? We’d love to hear from you.
//         </p>
//       </div>

//       <form
//         onSubmit={(e) => e.preventDefault()}
//         className="max-w-xl mx-auto space-y-4 bg-neutral-900 border border-white/10 p-6 rounded-xl"
//       >
//         <Input placeholder="Your name" required />
//         <Input placeholder="Your email" type="email" required />
//         <Textarea placeholder="Your message" rows={5} required />
//         <Button type="submit" className="w-full">
//           Send message
//         </Button>
//       </form>

//       <div className="max-w-xl mx-auto mt-12 space-y-4 text-white/70">
//         <p className="flex items-center gap-2">
//           <Mail className="h-5 w-5 text-indigo-400" /> support@linkly.io
//         </p>
//         <p className="flex items-center gap-2">
//           <Phone className="h-5 w-5 text-indigo-400" /> +91 90000 00000
//         </p>
//         <p className="flex items-center gap-2">
//           <MapPin className="h-5 w-5 text-indigo-400" /> Indore, M.P., India
//         </p>
//       </div>
//     </section>
//   );
// }

